// UFバッファ前提の3-style 120手順データ
const myThreeStyles = [
    // === 1文字目：「あ」 ===
    { buffer: "UF", sticker1: "あ", sticker2: "い", setup: "R2 U'", move1: "R2", move2: "S" },
    { buffer: "UF", sticker1: "あ", sticker2: "え", setup: "L2 U", move1: "L2", move2: "S'" },
    { buffer: "UF", sticker1: "あ", sticker2: "き", setup: "R' U'", move1: "R2", move2: "S" },
    { buffer: "UF", sticker1: "あ", sticker2: "く", setup: "R' F'", move1: "E", move2: "R U R'" },
    { buffer: "UF", sticker1: "あ", sticker2: "け", setup: "L U", move1: "L2", move2: "S'" },
    { buffer: "UF", sticker1: "あ", sticker2: "さ", setup: "U M U", move1: "M'", move2: "U2" },
    { buffer: "UF", sticker1: "あ", sticker2: "し", setup: "U", move1: "L' E L", move2: "U2" },
    { buffer: "UF", sticker1: "あ", sticker2: "す", setup: "U'", move1: "R E R'", move2: "U2" },
    { buffer: "UF", sticker1: "あ", sticker2: "せ", setup: "U", move1: "L E' L'", move2: "U2" },
    { buffer: "UF", sticker1: "あ", sticker2: "ち", setup: "L' U", move1: "S'", move2: "L2" },
    { buffer: "UF", sticker1: "あ", sticker2: "つ", setup: "U M' U", move1: "M'", move2: "U2" },
    { buffer: "UF", sticker1: "あ", sticker2: "て", setup: "R U'", move1: "S", move2: "R2" },
    { buffer: "UF", sticker1: "あ", sticker2: "な", setup: "U' M U'", move1: "M'", move2: "U2" },
    { buffer: "UF", sticker1: "あ", sticker2: "に", setup: "U'", move1: "R' E R", move2: "U2" },
    { buffer: "UF", sticker1: "あ", sticker2: "ぬ", setup: "U", move1: "L' E' L", move2: "U2" },
    { buffer: "UF", sticker1: "あ", sticker2: "ね", setup: "U'", move1: "R E' R'", move2: "U2" },
    { buffer: "UF", sticker1: "あ", sticker2: "は", setup: "", move1: "U2", move2: "M'" },
    { buffer: "UF", sticker1: "あ", sticker2: "ひ", setup: "U'", move1: "S", move2: "R2" },
    { buffer: "UF", sticker1: "あ", sticker2: "ふ", setup: "", move1: "M", move2: "U2" },
    { buffer: "UF", sticker1: "あ", sticker2: "へ", setup: "U", move1: "S'", move2: "L2" },

    // === 1文字目：「い」 ===
    { buffer: "UF", sticker1: "い", sticker2: "あ", setup: "R2 U'", move1: "S", move2: "R2" },
    { buffer: "UF", sticker1: "い", sticker2: "え", setup: "M2 U'", move1: "M", move2: "U2" },
    { buffer: "UF", sticker1: "い", sticker2: "き", setup: "E'", move1: "R' E R", move2: "U'" },
    { buffer: "UF", sticker1: "い", sticker2: "く", setup: "R", move1: "U' R' U", move2: "M'" },
    { buffer: "UF", sticker1: "い", sticker2: "け", setup: "", move1: "R E2 R'", move2: "U'" },
    { buffer: "UF", sticker1: "い", sticker2: "し", setup: "U", move1: "L' E L", move2: "U" },
    { buffer: "UF", sticker1: "い", sticker2: "す", setup: "", move1: "U'", move2: "R E R'" },
    { buffer: "UF", sticker1: "い", sticker2: "せ", setup: "U", move1: "L E' L'", move2: "U" },
    { buffer: "UF", sticker1: "い", sticker2: "た", setup: "", move1: "M", move2: "R' U' R U" },
    { buffer: "UF", sticker1: "い", sticker2: "ち", setup: "", move1: "U'", move2: "R' E2 R" },
    { buffer: "UF", sticker1: "い", sticker2: "つ", setup: "", move1: "U M U M' U M U M'", move2: "" },
    { buffer: "UF", sticker1: "い", sticker2: "て", setup: "U", move1: "L E2 L'", move2: "U" },
    { buffer: "UF", sticker1: "い", sticker2: "な", setup: "", move1: "S'", move2: "L F' L'" },
    { buffer: "UF", sticker1: "い", sticker2: "に", setup: "", move1: "U'", move2: "R' E R" },
    { buffer: "UF", sticker1: "い", sticker2: "ぬ", setup: "U", move1: "L' E' L", move2: "U" },
    { buffer: "UF", sticker1: "い", sticker2: "ね", setup: "", move1: "U'", move2: "R E' R'" },
    { buffer: "UF", sticker1: "い", sticker2: "は", setup: "R U R' U", move1: "M'", move2: "U2" },
    { buffer: "UF", sticker1: "い", sticker2: "ひ", setup: "", move1: "U' R E' R2 E R U R' E' R2 E R'", move2: "" },
    { buffer: "UF", sticker1: "い", sticker2: "ふ", setup: "M2", move1: "U' R' U", move2: "M2" },
    { buffer: "UF", sticker1: "い", sticker2: "へ", setup: "S' R' F R", move1: "S", move2: "R2" },

    // === 1文字目：「え」 ===
    { buffer: "UF", sticker1: "え", sticker2: "あ", setup: "L2 U", move1: "S'", move2: "L2" },
    { buffer: "UF", sticker1: "え", sticker2: "い", setup: "M2 U", move1: "M", move2: "U2" },
    { buffer: "UF", sticker1: "え", sticker2: "き", setup: "", move1: "L' E2 L", move2: "U" },
    { buffer: "UF", sticker1: "え", sticker2: "く", setup: "L'", move1: "U L U'", move2: "M'" },
    { buffer: "UF", sticker1: "え", sticker2: "け", setup: "E", move1: "L E' L'", move2: "U" },
    { buffer: "UF", sticker1: "え", sticker2: "さ", setup: "", move1: "S", move2: "R' F R" },
    { buffer: "UF", sticker1: "え", sticker2: "し", setup: "", move1: "U", move2: "L' E L" },
    { buffer: "UF", sticker1: "え", sticker2: "す", setup: "U'", move1: "R E R'", move2: "U'" },
    { buffer: "UF", sticker1: "え", sticker2: "せ", setup: "", move1: "U", move2: "L E' L'" },
    { buffer: "UF", sticker1: "え", sticker2: "た", setup: "", move1: "M", move2: "L U L' U'" },
    { buffer: "UF", sticker1: "え", sticker2: "ち", setup: "Uw", move1: "L' E L", move2: "U'" },
    { buffer: "UF", sticker1: "え", sticker2: "つ", setup: "", move1: "U' M U' M' U' M U' M'", move2: "" },
    { buffer: "UF", sticker1: "え", sticker2: "て", setup: "", move1: "U", move2: "L E2 L'" },
    { buffer: "UF", sticker1: "え", sticker2: "に", setup: "U'", move1: "R' E R", move2: "U'" },
    { buffer: "UF", sticker1: "え", sticker2: "ぬ", setup: "", move1: "U", move2: "L' E' L" },
    { buffer: "UF", sticker1: "え", sticker2: "ね", setup: "U'", move1: "R E' R'", move2: "U'" },
    { buffer: "UF", sticker1: "え", sticker2: "は", setup: "", move1: "M U2 M", move2: "U'" },
    { buffer: "UF", sticker1: "え", sticker2: "ひ", setup: "", move1: "U R U R' U' R' U' R' U R", move2: "" },
    { buffer: "UF", sticker1: "え", sticker2: "ふ", setup: "M2", move1: "U L U'", move2: "M2" },
    { buffer: "UF", sticker1: "え", sticker2: "へ", setup: "", move1: "L U' Rw E Rw2 E Rw U L'", move2: "" },

    // === 1文字目：「き」 ===
    { buffer: "UF", sticker1: "き", sticker2: "あ", setup: "R' U'", move1: "S", move2: "R2" },
    { buffer: "UF", sticker1: "き", sticker2: "い", setup: "E'", move1: "U'", move2: "R' E R" },
    { buffer: "UF", sticker1: "き", sticker2: "え", setup: "", move1: "U", move2: "L' E2 L" },
    { buffer: "UF", sticker1: "き", sticker2: "く", setup: "", move1: "U' R U", move2: "M'" },
    { buffer: "UF", sticker1: "き", sticker2: "け", setup: "R' U' R'", move1: "E", move2: "R2" },
    { buffer: "UF", sticker1: "き", sticker2: "さ", setup: "M'", move1: "R U R' U'", move2: "M'" },
    { buffer: "UF", sticker1: "き", sticker2: "し", setup: "", move1: "R U' R'", move2: "E'" },
    { buffer: "UF", sticker1: "き", sticker2: "す", setup: "R' Fw R'", move1: "S'", move2: "R2" },
    { buffer: "UF", sticker1: "き", sticker2: "た", setup: "", move1: "M", move2: "U' R U" },
    { buffer: "UF", sticker1: "き", sticker2: "ち", setup: "R' U' R'", move1: "E'", move2: "R2" },
    { buffer: "UF", sticker1: "き", sticker2: "つ", setup: "U L B'", move1: "E'", move2: "L2" },
    { buffer: "UF", sticker1: "き", sticker2: "て", setup: "U R'", move1: "S", move2: "R2" },
    { buffer: "UF", sticker1: "き", sticker2: "な", setup: "S' U L", move1: "E'", move2: "L2" },
    { buffer: "UF", sticker1: "き", sticker2: "に", setup: "", move1: "R U' R'", move2: "E" },
    { buffer: "UF", sticker1: "き", sticker2: "ぬ", setup: "D", move1: "M'", move2: "U' R U" },
    { buffer: "UF", sticker1: "き", sticker2: "ね", setup: "R", move1: "U'", move2: "R E' R'" },
    { buffer: "UF", sticker1: "き", sticker2: "は", setup: "", move1: "R' Fw2 R2 U' R2 Fw2 R2 U' R'", move2: "" },
    { buffer: "UF", sticker1: "き", sticker2: "ひ", setup: "", move1: "U R' U' R' U R U R U R' U2", move2: "" },
    { buffer: "UF", sticker1: "き", sticker2: "ふ", setup: "", move1: "M2", move2: "U' R U" },
    { buffer: "UF", sticker1: "き", sticker2: "へ", setup: "U L", move1: "E'", move2: "L2" },

    // === 1文字目：「く」 ===
    { buffer: "UF", sticker1: "く", sticker2: "あ", setup: "R' F'", move1: "R U R'", move2: "E" },
    { buffer: "UF", sticker1: "く", sticker2: "い", setup: "", move1: "M'", move2: "R U 'R' U" },
    { buffer: "UF", sticker1: "く", sticker2: "え", setup: "", move1: "M'", move2: "L' U L U'" },
    { buffer: "UF", sticker1: "く", sticker2: "き", setup: "", move1: "M'", move2: "U' R U" },
    { buffer: "UF", sticker1: "く", sticker2: "け", setup: "", move1: "M'", move2: "U L' U'" },
    { buffer: "UF", sticker1: "く", sticker2: "さ", setup: "M'", move1: "R U R' U'", move2: "M'" },
    { buffer: "UF", sticker1: "く", sticker2: "し", setup: "M'", move1: "U R' U'", move2: "M'" },
    { buffer: "UF", sticker1: "く", sticker2: "す", setup: "M'", move1: "U R2 U'", move2: "M'" },
    { buffer: "UF", sticker1: "く", sticker2: "せ", setup: "M'", move1: "U R U'", move2: "M'" },
    { buffer: "UF", sticker1: "く", sticker2: "た", setup: "D", move1: "U R2 U'", move2: "M" },
    { buffer: "UF", sticker1: "く", sticker2: "ち", setup: "", move1: "U L U'", move2: "M'" },
    { buffer: "UF", sticker1: "く", sticker2: "つ", setup: "", move1: "U M' U' M U2 M U M' U", move2: "" },
    { buffer: "UF", sticker1: "く", sticker2: "て", setup: "", move1: "U' R' U", move2: "M'" },
    { buffer: "UF", sticker1: "く", sticker2: "な", setup: "M'", move1: "L' U' L U", move2: "M'" },
    { buffer: "UF", sticker1: "く", sticker2: "に", setup: "M'", move1: "U' L' U", move2: "M'" },
    { buffer: "UF", sticker1: "く", sticker2: "ぬ", setup: "M'", move1: "U' L2 U", move2: "M'" },
    { buffer: "UF", sticker1: "く", sticker2: "ね", setup: "M'", move1: "U' L U", move2: "M'" },
    { buffer: "UF", sticker1: "く", sticker2: "ひ", setup: "", move1: "U' R2 U", move2: "M'" },
    { buffer: "UF", sticker1: "く", sticker2: "ふ", setup: "M' D", move1: "U R2 U'", move2: "M" },
    { buffer: "UF", sticker1: "く", sticker2: "へ", setup: "", move1: "U L2 U'", move2: "M'" },

    // === 1文字目：「け」 ===
    { buffer: "UF", sticker1: "け", sticker2: "あ", setup: "L U", move1: "S'", move2: "L2" },
    { buffer: "UF", sticker1: "け", sticker2: "い", setup: "", move1: "U'", move2: "R E2 R'" },
    { buffer: "UF", sticker1: "け", sticker2: "え", setup: "E", move1: "U", move2: "L E' L'" },
    { buffer: "UF", sticker1: "け", sticker2: "き", setup: "R' U' R", move1: "E", move2: "R2" },
    { buffer: "UF", sticker1: "け", sticker2: "く", setup: "", move1: "U L' U'", move2: "M'" },
    { buffer: "UF", sticker1: "け", sticker2: "さ", setup: "S U' R", move1: "R2", move2: "E" },
    { buffer: "UF", sticker1: "け", sticker2: "し", setup: "L'", move1: "U", move2: "L' E L" },
    { buffer: "UF", sticker1: "け", sticker2: "す", setup: "D'", move1: "M'", move2: "U L' U'" },
    { buffer: "UF", sticker1: "け", sticker2: "せ", setup: "", move1: "L' U L", move2: "E'" },
    { buffer: "UF", sticker1: "け", sticker2: "た", setup: "", move1: "M", move2: "U L' U'" },
    { buffer: "UF", sticker1: "け", sticker2: "ち", setup: "", move1: "U' Rw E Rw2 E Rw U", move2: "" },
    { buffer: "UF", sticker1: "け", sticker2: "つ", setup: "U' R' B", move1: "E", move2: "R2" },
    { buffer: "UF", sticker1: "け", sticker2: "て", setup: "R U' R'", move1: "E", move2: "R2" },
    { buffer: "UF", sticker1: "け", sticker2: "な", setup: "L U E L'", move1: "E'", move2: "L2" },
    { buffer: "UF", sticker1: "け", sticker2: "ぬ", setup: "S' U' R'", move1: "E", move2: "R2" },
    { buffer: "UF", sticker1: "け", sticker2: "は", setup: "", move1: "U' L' U' M' U2 M U' L U", move2: "" },
    { buffer: "UF", sticker1: "け", sticker2: "ひ", setup: "U' R'", move1: "E", move2: "R2" },
    { buffer: "UF", sticker1: "け", sticker2: "ふ", setup: "", move1: "M2", move2: "U R U'" },
    { buffer: "UF", sticker1: "け", sticker2: "へ", setup: "", move1: "D U' L' U' M' U2 M U' L U D'", move2: "" }
];
